### PR TITLE
Account for race condition with unwrap timeout.

### PR DESCRIPTION
**Pull request by benwiley4000**

### CODE REVIEW

**Comment by albertvision** [comment]
Hey @benwiley4000! Sorry for bothering you, but we are planning to release soon and would be happy to have your fix. Could you please release it, so we can use it? Thanks!

**Comment by benwiley4000** [comment]
I'm so sorry about this... Happens to me sometimes. I should have some time to take care of this *tonight.* Please bother me again if I don't but that's my plan. Penciling it in!

**Comment by benwiley4000** [comment]
@albertvision released!

**Comment by albertvision** [comment]
Thank you mate!

**Pull request merged**
