### PR TITLE
Fix unwrapping when no div is present in the fragment

### PR DESCRIPTION
**Pull request by albertvision**

### CODE REVIEW

**Comment by benwiley4000** [comment]
I can probably merge this.. but why would you render a Fragment with no children? Haha

**Comment by albertvision** [comment]
Haha, silly me! I meant when there's not a `div` in the fragment.

**Comment by benwiley4000** [comment]
Is your change fixing a bug on your end? I wasn't aware of a case where it was breaking.

**Comment by albertvision** [comment]
Yes, it breaks with the fragment I wrote in the previous comment.

**Comment by benwiley4000** [comment]
I still don't think I understand why it's breaking.. I reviewed the code and there's no reason `this.div` shouldn't exist at that point. If it doesn't then something else might not be working correctly. Could you give me a full short repro that I can run locally?

**Comment by albertvision** [comment]
Here you are: https://github.com/albertvision/react-dot-fragment-example.

What happens here is that the component that uses `Fragment` is asynchronously mounted and then unmounted, which represent the real case I have.

**Comment by benwiley4000** [comment]
@albertvision  I'm sorry for not seeing your reply last week. I'm reviewing your case now, thank you for taking the time to put it together!

**Comment by benwiley4000** [comment]
@albertvision thanks again for your repro case. It helped me understand the bug - it specifically happens when the Fragment is unmounted immediately after being mounted (I don't think your issue would occur if your toggle fired only once, not twice).

Although I understand why the fix you chose works, I think this one which is a bit more specific to the actual problem would be better since it leaves the code a bit less mysterious. What do you think - does this branch solve your issue?

https://github.com/benwiley4000/react-dot-fragment/compare/clear-timeout-on-unmount

**Comment by benwiley4000** [comment]
https://github.com/benwiley4000/react-dot-fragment/blob/2e8ba9b7755a1223612a32f4db503da3b9662323/index.js#L50

This is the line which really fixes the issue.

https://github.com/benwiley4000/react-dot-fragment/blob/2e8ba9b7755a1223612a32f4db503da3b9662323/index.js#L57

I don't think this is 100% necessary but it makes sure we empty the `this.orphans` array when we re-wrap. This way if we unmount immediately after a re-wrap (before the unwrap timeout has had a chance to fire) we don't repeat the re-wrap on unmount.

**Comment by apiportalJenkinks** [comment]
I like your solution, because it fixes the problem from its roots. 
Yes, it works perfectly!

**Comment by albertvision** [comment]
I like your solution, because it fixes the problem from its roots.
Yes, it works perfectly!

**Comment by benwiley4000** [comment]
Great thank you!

**Pull request closed without merging**
